# permissions for end users to view blockdevices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blockdevice-viewer-role
rules:
- apiGroups:
  - blockdevice.openebs.io
  resources:
  - blockdevices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blockdevice.openebs.io
  resources:
  - blockdevices/status
  verbs:
  - get
